/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { AiCallLogOutput } from '../model/aiCallLogOutput';
// @ts-ignore
import { AiCallLogSummaryOutput } from '../model/aiCallLogSummaryOutput';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class AIService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * List persisted AI call logs
     * @endpoint get /api/ai/logs
     * @param cityId 
     * @param contextType 
     * @param success 
     * @param fallbackUsed 
     * @param provider 
     * @param model 
     * @param limit 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listLogs(cityId?: number, contextType?: 'CHAT_FALLBACK' | 'EVENT_ENRICHMENT' | 'INVENTION_ENRICHMENT' | 'CHIEF_DECISION' | 'UNSPECIFIED', success?: boolean, fallbackUsed?: boolean, provider?: string, model?: string, limit?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<AiCallLogOutput>>;
    public listLogs(cityId?: number, contextType?: 'CHAT_FALLBACK' | 'EVENT_ENRICHMENT' | 'INVENTION_ENRICHMENT' | 'CHIEF_DECISION' | 'UNSPECIFIED', success?: boolean, fallbackUsed?: boolean, provider?: string, model?: string, limit?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<AiCallLogOutput>>>;
    public listLogs(cityId?: number, contextType?: 'CHAT_FALLBACK' | 'EVENT_ENRICHMENT' | 'INVENTION_ENRICHMENT' | 'CHIEF_DECISION' | 'UNSPECIFIED', success?: boolean, fallbackUsed?: boolean, provider?: string, model?: string, limit?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<AiCallLogOutput>>>;
    public listLogs(cityId?: number, contextType?: 'CHAT_FALLBACK' | 'EVENT_ENRICHMENT' | 'INVENTION_ENRICHMENT' | 'CHIEF_DECISION' | 'UNSPECIFIED', success?: boolean, fallbackUsed?: boolean, provider?: string, model?: string, limit?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>cityId, 'cityId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>contextType, 'contextType');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>success, 'success');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>fallbackUsed, 'fallbackUsed');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>provider, 'provider');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>model, 'model');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>limit, 'limit');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer-jwt) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer-jwt', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/ai/logs`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<AiCallLogOutput>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Aggregate persisted AI call logs
     * @endpoint get /api/ai/logs/summary
     * @param cityId 
     * @param contextType 
     * @param success 
     * @param fallbackUsed 
     * @param provider 
     * @param model 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public summarizeLogs(cityId?: number, contextType?: 'CHAT_FALLBACK' | 'EVENT_ENRICHMENT' | 'INVENTION_ENRICHMENT' | 'CHIEF_DECISION' | 'UNSPECIFIED', success?: boolean, fallbackUsed?: boolean, provider?: string, model?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<AiCallLogSummaryOutput>;
    public summarizeLogs(cityId?: number, contextType?: 'CHAT_FALLBACK' | 'EVENT_ENRICHMENT' | 'INVENTION_ENRICHMENT' | 'CHIEF_DECISION' | 'UNSPECIFIED', success?: boolean, fallbackUsed?: boolean, provider?: string, model?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiCallLogSummaryOutput>>;
    public summarizeLogs(cityId?: number, contextType?: 'CHAT_FALLBACK' | 'EVENT_ENRICHMENT' | 'INVENTION_ENRICHMENT' | 'CHIEF_DECISION' | 'UNSPECIFIED', success?: boolean, fallbackUsed?: boolean, provider?: string, model?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiCallLogSummaryOutput>>;
    public summarizeLogs(cityId?: number, contextType?: 'CHAT_FALLBACK' | 'EVENT_ENRICHMENT' | 'INVENTION_ENRICHMENT' | 'CHIEF_DECISION' | 'UNSPECIFIED', success?: boolean, fallbackUsed?: boolean, provider?: string, model?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>cityId, 'cityId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>contextType, 'contextType');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>success, 'success');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>fallbackUsed, 'fallbackUsed');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>provider, 'provider');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>model, 'model');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer-jwt) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer-jwt', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/ai/logs/summary`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiCallLogSummaryOutput>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
