/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgentUiEffectOutput { 
    type?: string;
    humanId?: number;
    eventId?: number;
    inventionId?: number;
    fromTick?: number;
    panel?: string;
    placeId?: string;
    eventType?: string;
    eventIds?: Array<number>;
}

