/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentActionOutput } from './agentActionOutput';
import { AgentReferencedEntitiesOutput } from './agentReferencedEntitiesOutput';
import { AgentUiEffectOutput } from './agentUiEffectOutput';


export interface AgentChatResponseOutput { 
    conversationId?: string;
    message?: string;
    commandClass?: string;
    interpretationProvenance?: string;
    interpretedCommandSummary?: string;
    executedActions?: Array<AgentActionOutput>;
    referencedEntities?: AgentReferencedEntitiesOutput;
    uiEffects?: Array<AgentUiEffectOutput>;
    structuredData?: { [key: string]: any; };
}

