/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgentChatRequestInput { 
    message?: string;
    conversationId?: string;
    selectedHumanId?: number;
    selectedEventId?: number;
    selectedInventionId?: number;
    confirmationToken?: string;
    confirmIntervention?: boolean;
}

