/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiCallLogContextSummaryOutput { 
    contextType?: string;
    totalCount?: number;
    successCount?: number;
    failureCount?: number;
    fallbackCount?: number;
}

