/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiCallLogOutput { 
    id?: number;
    timestamp?: string;
    cityId?: number;
    contextType?: string;
    contextEntityType?: string;
    contextEntityId?: string;
    provider?: string;
    model?: string;
    success?: boolean;
    fallbackUsed?: boolean;
    durationMs?: number;
    promptSummary?: string;
    promptHash?: string;
    responseHash?: string;
    errorCode?: string;
    errorMessage?: string;
}

