/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiCallLogContextSummaryOutput } from './aiCallLogContextSummaryOutput';


export interface AiCallLogSummaryOutput { 
    totalCount?: number;
    successCount?: number;
    failureCount?: number;
    fallbackCount?: number;
    byContextType?: Array<AiCallLogContextSummaryOutput>;
}

