/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CityOverviewOutput { 
    cityId: number;
    cityName: string;
    hasRun: boolean;
    runStatus?: CityOverviewOutput.RunStatusEnum;
    running: boolean;
    tick: number;
    year: number;
    era: CityOverviewOutput.EraEnum;
    population: number;
    inventionCount: number;
    eventCount: number;
    discoveryUnlockCount: number;
    unlockedInventionCount: number;
    applicationUnlockCount: number;
    updatedAt?: string;
}
export namespace CityOverviewOutput {
    export const RunStatusEnum = {
        Created: 'CREATED',
        Running: 'RUNNING',
        Paused: 'PAUSED',
        Completed: 'COMPLETED'
    } as const;
    export type RunStatusEnum = typeof RunStatusEnum[keyof typeof RunStatusEnum];
    export const EraEnum = {
        Founding: 'FOUNDING',
        Expansion: 'EXPANSION',
        Consolidation: 'CONSOLIDATION',
        Legacy: 'LEGACY'
    } as const;
    export type EraEnum = typeof EraEnum[keyof typeof EraEnum];
}


