/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventOutput { 
    id: number;
    cityId: number;
    tick: number;
    sequenceInTick: number;
    eventCategory: EventOutput.EventCategoryEnum;
    eventType: EventOutput.EventTypeEnum;
    actorIds: Array<number>;
    payload: { [key: string]: string; };
    importance: number;
    year: number;
    era: EventOutput.EraEnum;
    eventKey: string;
    title?: string;
    summary?: string;
    createdAt: string;
    enrichmentStatus: EventOutput.EnrichmentStatusEnum;
    enrichmentFallback: boolean;
    enrichedSnippet?: string;
    enrichmentProvider?: string;
    enrichmentModel?: string;
    enrichmentUpdatedAt?: string;
}
export namespace EventOutput {
    export const EventCategoryEnum = {
        Lifecycle: 'LIFECYCLE',
        Interaction: 'INTERACTION',
        Discovery: 'DISCOVERY',
        Dialogue: 'DIALOGUE',
        Milestone: 'MILESTONE'
    } as const;
    export type EventCategoryEnum = typeof EventCategoryEnum[keyof typeof EventCategoryEnum];
    export const EventTypeEnum = {
        SimulationStarted: 'SIMULATION_STARTED',
        SimulationPaused: 'SIMULATION_PAUSED',
        SimulationResumed: 'SIMULATION_RESUMED',
        SimulationCompleted: 'SIMULATION_COMPLETED',
        HumansCollided: 'HUMANS_COLLIDED',
        GoalAssigned: 'GOAL_ASSIGNED',
        GoalCompleted: 'GOAL_COMPLETED',
        HumanActionPerformed: 'HUMAN_ACTION_PERFORMED',
        DiscoveryUnlocked: 'DISCOVERY_UNLOCKED',
        DialogueExchanged: 'DIALOGUE_EXCHANGED',
        InventionEmerged: 'INVENTION_EMERGED',
        TribePlaceDiscovered: 'TRIBE_PLACE_DISCOVERED',
        TribeDiscoveryReported: 'TRIBE_DISCOVERY_REPORTED',
        TribeScoutReport: 'TRIBE_SCOUT_REPORT',
        TribePlanChosen: 'TRIBE_PLAN_CHOSEN',
        TribeGroupTravelCoordinated: 'TRIBE_GROUP_TRAVEL_COORDINATED'
    } as const;
    export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];
    export const EraEnum = {
        Founding: 'FOUNDING',
        Expansion: 'EXPANSION',
        Consolidation: 'CONSOLIDATION',
        Legacy: 'LEGACY'
    } as const;
    export type EraEnum = typeof EraEnum[keyof typeof EraEnum];
    export const EnrichmentStatusEnum = {
        None: 'NONE',
        Ready: 'READY',
        Fallback: 'FALLBACK'
    } as const;
    export type EnrichmentStatusEnum = typeof EnrichmentStatusEnum[keyof typeof EnrichmentStatusEnum];
}


