/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InventionOutput { 
    id: number;
    cityId: number;
    tickCreated: number;
    category: InventionOutput.CategoryEnum;
    inventionKey: string;
    title: string;
    summary: string;
    sourceEventKeys: Array<string>;
    impactScore: number;
    yearCreated: number;
    eraCreated: InventionOutput.EraCreatedEnum;
    createdAt: string;
    enrichmentStatus: InventionOutput.EnrichmentStatusEnum;
    enrichmentFallback: boolean;
    enrichedTitle?: string;
    enrichedSummary?: string;
    enrichmentProvider?: string;
    enrichmentModel?: string;
    enrichmentUpdatedAt?: string;
}
export namespace InventionOutput {
    export const CategoryEnum = {
        Technique: 'TECHNIQUE',
        SocialPractice: 'SOCIAL_PRACTICE',
        Knowledge: 'KNOWLEDGE'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
    export const EraCreatedEnum = {
        Founding: 'FOUNDING',
        Expansion: 'EXPANSION',
        Consolidation: 'CONSOLIDATION',
        Legacy: 'LEGACY'
    } as const;
    export type EraCreatedEnum = typeof EraCreatedEnum[keyof typeof EraCreatedEnum];
    export const EnrichmentStatusEnum = {
        None: 'NONE',
        Ready: 'READY',
        Fallback: 'FALLBACK'
    } as const;
    export type EnrichmentStatusEnum = typeof EnrichmentStatusEnum[keyof typeof EnrichmentStatusEnum];
}


