/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationSnapshotBoundsOutput } from './simulationSnapshotBoundsOutput';
import { SimulationSnapshotCentroidOutput } from './simulationSnapshotCentroidOutput';


export interface SimulationSnapshotMetricsOutput { 
    population: number;
    busyCount: number;
    busyRatio: number;
    centroid?: SimulationSnapshotCentroidOutput;
    bounds?: SimulationSnapshotBoundsOutput;
    eventCount: number;
    inventionCount: number;
}

