/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimulationSnapshotHumanOutput { 
    id: number;
    name: string;
    tribeId?: string;
    tribeRole?: string;
    x?: number;
    y?: number;
    busy: boolean;
}

