/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationCommandBuilderActionOutput } from './simulationCommandBuilderActionOutput';
import { SimulationCommandBuilderOptionOutput } from './simulationCommandBuilderOptionOutput';


export interface SimulationCommandBuilderOutput { 
    actorOptions?: Array<SimulationCommandBuilderOptionOutput>;
    actions?: Array<SimulationCommandBuilderActionOutput>;
}

