/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimulationSnapshotRunOutput { 
    hasRun: boolean;
    runId?: number;
    seed?: number;
    status?: SimulationSnapshotRunOutput.StatusEnum;
    running: boolean;
    tick: number;
    year: number;
    era: SimulationSnapshotRunOutput.EraEnum;
    createdAt?: string;
    updatedAt?: string;
}
export namespace SimulationSnapshotRunOutput {
    export const StatusEnum = {
        Created: 'CREATED',
        Running: 'RUNNING',
        Paused: 'PAUSED',
        Completed: 'COMPLETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const EraEnum = {
        Founding: 'FOUNDING',
        Expansion: 'EXPANSION',
        Consolidation: 'CONSOLIDATION',
        Legacy: 'LEGACY'
    } as const;
    export type EraEnum = typeof EraEnum[keyof typeof EraEnum];
}


