/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationCommandBuilderOptionOutput } from './simulationCommandBuilderOptionOutput';


export interface SimulationCommandBuilderActionOutput { 
    actionKey?: string;
    label?: string;
    executionKind?: string;
    actorKind?: string;
    targetKind?: string;
    commandText?: string;
    commandVerb?: string;
    requiresDifferentTarget?: boolean;
    targetOptions?: Array<SimulationCommandBuilderOptionOutput>;
}

