/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimulationAssistantCommandDescriptorOutput { 
    commandType?: string;
    canonicalText?: string;
    label?: string;
    description?: string;
}

