/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimulationSnapshotBoundsOutput { 
    minX?: number;
    maxX?: number;
    minY?: number;
    maxY?: number;
}

