/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationAssistantItemOutput } from './simulationAssistantItemOutput';
import { SimulationAssistantMetricOutput } from './simulationAssistantMetricOutput';


export interface SimulationAssistantBlockOutput { 
    type?: string;
    title?: string;
    subtitle?: string;
    metrics?: Array<SimulationAssistantMetricOutput>;
    items?: Array<SimulationAssistantItemOutput>;
    emptyState?: string;
}

