/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationSnapshotCityOutput } from './simulationSnapshotCityOutput';
import { SimulationTimelineSummaryOutput } from './simulationTimelineSummaryOutput';
import { SimulationSnapshotHumanOutput } from './simulationSnapshotHumanOutput';
import { EventOutput } from './eventOutput';
import { InventionOutput } from './inventionOutput';
import { SimulationSnapshotRunOutput } from './simulationSnapshotRunOutput';
import { SimulationSnapshotMetricsOutput } from './simulationSnapshotMetricsOutput';


export interface SimulationSnapshotOutput { 
    city: SimulationSnapshotCityOutput;
    run: SimulationSnapshotRunOutput;
    timelineSummary: SimulationTimelineSummaryOutput;
    humans: Array<SimulationSnapshotHumanOutput>;
    metrics: SimulationSnapshotMetricsOutput;
    recentEvents: Array<EventOutput>;
    recentInventions: Array<InventionOutput>;
}

