/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimulationKnowledgeOutput { 
    unlockedDiscoveries: Array<string>;
    unlockedInventions: Array<string>;
    unlockedApplications: Array<string>;
}

