/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationCommandReferencedEntitiesOutput } from './simulationCommandReferencedEntitiesOutput';
import { AgentUiEffectOutput } from './agentUiEffectOutput';


export interface SimulationCommandOutput { 
    ok?: boolean;
    commandType?: string;
    message?: string;
    mutated?: boolean;
    referencedEntities?: SimulationCommandReferencedEntitiesOutput;
    uiEffects?: Array<AgentUiEffectOutput>;
}

