/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimulationRunOutput { 
    id: number;
    cityId: number;
    seed: number;
    tick: number;
    status: SimulationRunOutput.StatusEnum;
    running: boolean;
    createdAt: string;
    updatedAt: string;
}
export namespace SimulationRunOutput {
    export const StatusEnum = {
        Created: 'CREATED',
        Running: 'RUNNING',
        Paused: 'PAUSED',
        Completed: 'COMPLETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


