/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventOutput } from './eventOutput';
import { InventionOutput } from './inventionOutput';


export interface TimelineOutput { 
    cityId: number;
    fromTick: number;
    toTick?: number;
    eventCount: number;
    inventionCount: number;
    events: Array<EventOutput>;
    inventions: Array<InventionOutput>;
}

