/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TribeKnownPlaceOutput } from './tribeKnownPlaceOutput';
import { TribeHouseOutput } from './tribeHouseOutput';


export interface TribeSnapshotOutput { 
    tribeId: string;
    house: TribeHouseOutput;
    scoutHumanId: number;
    knownPlaces: Array<TribeKnownPlaceOutput>;
}

