ALTER TABLE human
    ADD COLUMN IF NOT EXISTS tribe_role VARCHAR(32);

CREATE TABLE tribe_house (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    tribe_id VARCHAR(64) NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_tribe_house_city_tribe UNIQUE (city_id, tribe_id),
    CONSTRAINT fk_tribe_house_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE tribe_known_place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    tribe_id VARCHAR(64) NOT NULL,
    place_id VARCHAR(64) NOT NULL,
    discovered_by_human_id BIGINT NOT NULL,
    discovered_tick BIGINT NOT NULL,
    reported_tick BIGINT,
    reported BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_tribe_known_place_city_tribe_place UNIQUE (city_id, tribe_id, place_id),
    CONSTRAINT fk_tribe_known_place_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE INDEX idx_tribe_house_city_tribe ON tribe_house(city_id, tribe_id);
CREATE INDEX idx_tribe_known_place_city_tribe ON tribe_known_place(city_id, tribe_id, discovered_tick);
