CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT,
    name VARCHAR(255),
    CONSTRAINT fk_city_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE human (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    busy BOOLEAN NOT NULL,
    name VARCHAR(255),
    x DOUBLE PRECISION,
    y DOUBLE PRECISION,
    creativity DOUBLE PRECISION,
    intellect DOUBLE PRECISION,
    sociability DOUBLE PRECISION,
    practicality DOUBLE PRECISION,
    personality INTEGER,
    science_skill DOUBLE PRECISION,
    culture_skill DOUBLE PRECISION,
    social_skill DOUBLE PRECISION,
    total_science_contributed DOUBLE PRECISION,
    total_culture_contributed DOUBLE PRECISION,
    total_social_contributed DOUBLE PRECISION,
    city_id BIGINT,
    CONSTRAINT fk_human_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE simulation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    seed BIGINT NOT NULL,
    tick BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_simulation_run_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE interaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE history_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    tick BIGINT NOT NULL,
    sequence_in_tick INTEGER NOT NULL,
    event_category VARCHAR(32) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload VARCHAR(4000) NOT NULL,
    importance INTEGER NOT NULL,
    event_year INTEGER NOT NULL,
    era VARCHAR(32) NOT NULL,
    event_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    enrichment_status VARCHAR(16) NOT NULL DEFAULT 'NONE',
    enrichment_fallback BOOLEAN NOT NULL DEFAULT FALSE,
    enriched_snippet VARCHAR(2000),
    enrichment_provider VARCHAR(64),
    enrichment_model VARCHAR(128),
    enrichment_updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_history_event_city_key UNIQUE (city_id, event_key),
    CONSTRAINT fk_history_event_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE history_event_actor_ids (
    actor_index INTEGER NOT NULL,
    actor_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    PRIMARY KEY (actor_index, event_id),
    CONSTRAINT fk_history_event_actor_ids_event FOREIGN KEY (event_id) REFERENCES history_event(id)
);

CREATE TABLE history_invention (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    tick_created BIGINT NOT NULL,
    category VARCHAR(32) NOT NULL,
    invention_key VARCHAR(128) NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(1000) NOT NULL,
    impact_score INTEGER NOT NULL,
    year_created INTEGER NOT NULL,
    era_created VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    enrichment_status VARCHAR(16) NOT NULL DEFAULT 'NONE',
    enrichment_fallback BOOLEAN NOT NULL DEFAULT FALSE,
    enriched_title VARCHAR(200),
    enriched_summary VARCHAR(2000),
    enrichment_provider VARCHAR(64),
    enrichment_model VARCHAR(128),
    enrichment_updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_history_invention_city_key UNIQUE (city_id, invention_key),
    CONSTRAINT fk_history_invention_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE history_invention_source_event_keys (
    source_index INTEGER NOT NULL,
    invention_id BIGINT NOT NULL,
    source_event_key VARCHAR(128) NOT NULL,
    PRIMARY KEY (source_index, invention_id),
    CONSTRAINT fk_history_invention_source_event_keys_invention FOREIGN KEY (invention_id) REFERENCES history_invention(id)
);

CREATE INDEX idx_history_event_city_tick_seq ON history_event(city_id, tick, sequence_in_tick);
CREATE INDEX idx_history_event_city_type ON history_event(city_id, event_type);
CREATE INDEX idx_history_invention_city_tick ON history_invention(city_id, tick_created);
CREATE INDEX idx_history_invention_city_category ON history_invention(city_id, category);
