CREATE TABLE director_intervention (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    initiated_by_user_id BIGINT NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    confirmation_token VARCHAR(64) NOT NULL UNIQUE,
    confirmation_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    summary VARCHAR(512),
    requested_at_tick BIGINT,
    executed_at_tick BIGINT,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE director_intervention_actor_ids (
    actor_index INTEGER NOT NULL,
    intervention_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    PRIMARY KEY (actor_index, intervention_id),
    CONSTRAINT fk_director_intervention_actor_ids_intervention
        FOREIGN KEY (intervention_id) REFERENCES director_intervention(id)
);

CREATE INDEX idx_director_intervention_city_status
    ON director_intervention(city_id, status);
