CREATE TABLE simulation_goal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id BIGINT NOT NULL,
    goal_type VARCHAR(40) NOT NULL,
    status VARCHAR(24) NOT NULL,
    source VARCHAR(40) NOT NULL,
    assigned_tick BIGINT NOT NULL,
    completed_tick BIGINT,
    target_place_id VARCHAR(64),
    target_human_id BIGINT,
    target_x DOUBLE PRECISION,
    target_y DOUBLE PRECISION,
    metadata_key VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_simulation_goal_human FOREIGN KEY (human_id) REFERENCES human(id)
);

CREATE INDEX idx_simulation_goal_human_status_assigned
    ON simulation_goal(human_id, status, assigned_tick DESC, id DESC);
CREATE INDEX idx_simulation_goal_city_active
    ON simulation_goal(status, assigned_tick, human_id);
