CREATE TABLE simulation_knowledge_unlock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    node_type VARCHAR(24) NOT NULL,
    unlocked_tick BIGINT NOT NULL,
    trigger_event_type VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_knowledge_unlock_city_node UNIQUE (city_id, node_id),
    CONSTRAINT fk_knowledge_unlock_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE INDEX idx_knowledge_unlock_city_tick
    ON simulation_knowledge_unlock(city_id, unlocked_tick, node_id);
