CREATE TABLE simulation_tribe_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    tribe_id VARCHAR(64) NOT NULL,
    chief_human_id BIGINT,
    plan_type VARCHAR(32),
    plan_status VARCHAR(24) NOT NULL,
    target_place_id VARCHAR(64),
    decision_source VARCHAR(24),
    reason_summary VARCHAR(500),
    plan_metadata_key VARCHAR(128),
    last_assigned_tick BIGINT,
    completed_tick BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_simulation_tribe_plan_city_tribe UNIQUE (city_id, tribe_id),
    CONSTRAINT fk_simulation_tribe_plan_city FOREIGN KEY (city_id) REFERENCES city(id),
    CONSTRAINT fk_simulation_tribe_plan_chief FOREIGN KEY (chief_human_id) REFERENCES human(id)
);

CREATE TABLE simulation_tribe_plan_assigned_humans (
    assignment_index INTEGER NOT NULL,
    tribe_plan_id BIGINT NOT NULL,
    human_id BIGINT NOT NULL,
    PRIMARY KEY (assignment_index, tribe_plan_id),
    CONSTRAINT fk_simulation_tribe_plan_assigned_humans_plan FOREIGN KEY (tribe_plan_id) REFERENCES simulation_tribe_plan(id)
);

CREATE INDEX idx_simulation_tribe_plan_city_status
    ON simulation_tribe_plan(city_id, plan_status, tribe_id);

CREATE TABLE ai_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    city_id BIGINT,
    context_type VARCHAR(40) NOT NULL,
    context_entity_type VARCHAR(64),
    context_entity_id VARCHAR(128),
    provider VARCHAR(32),
    model VARCHAR(128),
    success BOOLEAN NOT NULL,
    fallback_used BOOLEAN NOT NULL,
    duration_ms BIGINT NOT NULL,
    prompt_summary VARCHAR(500),
    prompt_hash VARCHAR(64),
    response_hash VARCHAR(64),
    error_code VARCHAR(128),
    error_message VARCHAR(500),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_call_log_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE INDEX idx_ai_call_log_requested_at
    ON ai_call_log(requested_at DESC, id DESC);

CREATE INDEX idx_ai_call_log_city_context
    ON ai_call_log(city_id, context_type, success);
